type Attachment {
  id: ID!
  name: String!
}

enum ToDoStatus {
  OPEN
  CLOSED
  DELETED
}

type ToDo {
  id: ID!
  title: String!
  status: ToDoStatus!
  body: String!
  attachments: [Attachment!]!
  attachmentCount: Int!
}

input EditToDoChanges {
  title: String
  body: String
}

type Mutation {
  createToDo(title: String!): ToDo!
  closeToDo(id: ID!): ToDo!
  openToDo(id: ID!): ToDo!
  editToDo(id: ID!, changes: EditToDoChanges!): ToDo!
  deleteToDo(id: ID!): Boolean
  addAttachment(toDo: ID!, name: String!): Attachment!
  removeAttachment(id: ID!): Boolean!
}

type Query {
  todos(statuses: [ToDoStatus!]): [ToDo!]!
  todo(id: ID!): ToDo!
}
